# Generated by Django 5.0.7 on 2024-08-15 09:29

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdef123456', length=10, max_length=20, prefix='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfferProduct',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdef123456', length=10, max_length=20, prefix='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayProduct',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdef123456', length=10, max_length=20, prefix='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=100)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartmobicell.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdef123456', length=10, max_length=20, prefix='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartmobicell.category')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
