# Generated by Django 5.0.7 on 2024-08-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartmobicell', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
