# Generated by Django 5.0.7 on 2024-08-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmobicell', '0003_displayproduct_image_offerproduct_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='smartmobicell/files/media'),
        ),
        migrations.AlterField(
            model_name='offerproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='smartmobicell/files/media'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='smartmobicell/files/media'),
        ),
    ]
