# Generated by Django 5.0.7 on 2024-08-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmobicell', '0005_alter_displayproduct_image_alter_offerproduct_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='smartmobicell/media/files'),
        ),
        migrations.AlterField(
            model_name='offerproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='smartmobicell/media/files'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='smartmobicell/media/files'),
        ),
    ]
